#!/usr/bin/env ruby
# frozen_string_literal: true

require "omniai/openai"

client = OmniAI::OpenAI::Client.new

File.open(File.join(__dir__, "audio.wav"), "rb") do |file|
  puts client.transcribe(file).text
end
