#!/usr/bin/env ruby
# frozen_string_literal: true

require "omniai/openai"

CLIENT = OmniAI::OpenAI::Client.new

File.open(File.join(__dir__, "audio.wav"), "rb") do |file|
  transcription = CLIENT.transcribe(file)
  puts(transcription.text)
end
