#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "omniai"

client = OmniAI::OpenAI::Client.new

File.open(File.join(__dir__, "files/audio.wav"), "rb") do |file|
  transcription = client.transcribe(file, format: OmniAI::Transcribe::Format::VERBOSE_JSON)
  puts "Duration: #{transcription.duration}"
  puts "Language: #{transcription.language}"
  puts "Text: #{transcription.text}"
end
