#!/usr/bin/env ruby
# frozen_string_literal: true

require "omniai/openai"

client = OmniAI::OpenAI::Client.new

File.open(File.join(__dir__, "files/audio.wav"), "wb") do |file|
  client.speak("Sally sells seashells by the seashore.", format: OmniAI::Speak::Format::WAV) do |chunk|
    file << chunk
  end
end
